export const TOOLTIPS = {
  arr: 'Annual Recurring Revenue. Your MRR multiplied by 12. Investors use ARR to gauge the scale of your recurring revenue business.',
  mrr: 'Monthly Recurring Revenue. The predictable revenue you earn each month from subscriptions. This is the #1 metric seed investors look at.',
  mrrGrowth: 'Month-over-month MRR growth rate. Seed-stage VCs typically want to see 15-20% MoM growth. Calculated as (current MRR - previous MRR) / previous MRR.',
  nrr: 'Net Revenue Retention. Measures how much revenue you keep and expand from existing customers over time. Above 100% means expansion revenue exceeds churn. Best-in-class SaaS companies have NRR > 120%.',
  grossRetention: 'Gross Revenue Retention. Revenue kept from existing customers before expansion. Measures pure churn impact. Target: > 85% for SaaS.',
  ltvCac: 'Lifetime Value to Customer Acquisition Cost ratio. Measures unit economics health. LTV/CAC > 3x is the benchmark VCs look for. Below 1x means you lose money on every customer.',
  ltv: 'Customer Lifetime Value. The total revenue you expect from a single customer over their entire relationship with you. Calculated as (ARPU x Gross Margin) / Monthly Churn Rate.',
  cac: 'Customer Acquisition Cost. How much you spend to acquire one new customer, including all marketing and sales costs. Lower is better, but too low may mean under-investing in growth.',
  arpu: 'Average Revenue Per User (per month). Your MRR divided by total customers. Tracking ARPU growth shows pricing power.',
  churnRate: 'Monthly customer churn rate. The percentage of customers who cancel each month. For SaaS, < 5% monthly (< 50% annual) is typical at seed stage. Best-in-class is < 2%.',
  burnRate: 'Net Burn Rate. How much cash you spend beyond what you earn each month. Calculated as operating expenses minus revenue.',
  burnMultiple: 'Burn Multiple. Net burn divided by net new MRR. Measures capital efficiency — how much you burn to generate each dollar of new ARR. Below 2x is excellent, 2-4x is good, above 4x needs attention.',
  runway: 'Cash Runway. How many months until you run out of cash at current burn rate. VCs want to see 12-18 months of runway when you raise.',
  grossMargin: 'Gross Margin. Revenue minus cost of goods sold (hosting, payment processing, support), as a percentage of revenue. SaaS companies typically have 70-85% gross margins.',
  paybackMonths: 'CAC Payback Period. Months to recover the cost of acquiring a customer from their gross profit contribution. Calculated as CAC / (ARPU x Gross Margin). Under 12 months is strong for seed stage.',
  tam: 'Total Addressable Market. The total revenue opportunity if you captured 100% of the market. Think of it as the ceiling for your business. Use a top-down or bottom-up approach.',
  sam: 'Serviceable Addressable Market. The portion of TAM you can realistically reach with your current product and go-to-market strategy.',
  som: 'Serviceable Obtainable Market. The realistic revenue you can capture in the near term, given competition and your current resources.',
  dcf: 'Discounted Cash Flow. A valuation method that estimates company value based on projected future cash flows, discounted back to present value. More common for later-stage companies.',
  vcMethod: 'VC Method Valuation. Values your company by estimating exit value (revenue x exit multiple), then working backward using the investor\'s target return to find today\'s pre-money valuation. This is how most seed VCs actually think about valuation.',
  discountRate: 'Discount Rate (WACC). The rate used to discount future cash flows to present value. For early-stage startups, 25-40% is typical, reflecting high risk.',
  terminalGrowth: 'Terminal Growth Rate. The assumed perpetual growth rate after the projection period ends. Usually 2-3%, roughly matching GDP growth.',
  ebitda: 'Earnings Before Interest, Taxes, Depreciation, and Amortization. A proxy for operating profitability. Most seed-stage startups are EBITDA-negative — that\'s expected.',
  ebitdaMargin: 'EBITDA as a percentage of revenue. Shows operating leverage. Mature SaaS companies target 20-30% EBITDA margins.',
  freeCashFlow: 'Free Cash Flow. Cash generated from operations minus capital expenditures. The actual cash your business produces (or consumes).',
  userGrowth: 'Annual user/customer growth rate. How fast your customer base grows year-over-year. Seed-stage SaaS companies often target 2-3x annual growth.',
  expansionRate: 'Revenue Expansion Rate. The percentage of additional revenue generated from existing customers through upsells, cross-sells, or usage growth.',
  revenuePerEmployee: 'Revenue per Employee. Total revenue divided by headcount. A measure of team efficiency. Early-stage is typically $100-200K; mature SaaS targets $200-400K+.',
  marketShare: 'Your total revenue as a percentage of the Serviceable Addressable Market (SAM). Shows your penetration of the addressable market.',
  safetyBuffer: 'Extra cash cushion added to the calculated funding need. Accounts for unexpected expenses or slower-than-projected growth.',
  salesEfficiency: 'Magic Number. Net new ARR divided by sales & marketing spend. Above 1.0 means efficient growth; below 0.5 suggests go-to-market issues.',
  dilution: 'Ownership percentage given to new investors in a funding round. Calculated as round size / post-money valuation. Typical seed dilution is 15-25%.',
  preMoney: 'Pre-Money Valuation. Your company\'s value before the new investment. Pre-money + round size = post-money valuation.',
  postMoney: 'Post-Money Valuation. Your company\'s value after the new investment is added. This determines how much ownership investors get.',
  capTable: 'Capitalization Table. Shows who owns what percentage of the company. Critical for understanding dilution across funding rounds.',
  scurveGrowth: 'S-Curve Growth Model. Models growth as a logistic curve that starts slow, accelerates, then plateaus as you approach market saturation. More realistic than constant compound growth for mature markets.',
  hostingCost: 'Per-user hosting cost (monthly). Infrastructure costs like cloud servers, databases, CDN. Typical SaaS: $0.10-$2.00 per user/month depending on compute intensity.',
  paymentProcessing: 'Payment processing fee as a percentage of revenue. Stripe/PayPal typically charge 2.9% + $0.30 per transaction. Default: 3%.',
  supportCost: 'Per-user customer support cost (monthly). Includes helpdesk tools, support staff allocation. Typical: $0.10-$1.00 per user/month.',
} as const;

export type TooltipKey = keyof typeof TOOLTIPS;
