CREATE TABLE IF NOT EXISTS "model_metrics" (
  "id" serial PRIMARY KEY NOT NULL,
  "model_id" integer NOT NULL REFERENCES "financial_models"("id") ON DELETE cascade,
  "users_total" numeric(18, 4),
  "dau" numeric(18, 4),
  "mau" numeric(18, 4),
  "growth_rate" numeric(10, 4),
  "activation_rate" numeric(10, 4),
  "retention_rate" numeric(10, 4),
  "churn_rate" numeric(10, 4),
  "mrr" numeric(18, 4),
  "arr" numeric(18, 4),
  "arpu" numeric(18, 4),
  "revenue_growth_rate" numeric(10, 4),
  "expansion_revenue" numeric(18, 4),
  "contraction_revenue" numeric(18, 4),
  "cac" numeric(18, 4),
  "ltv" numeric(18, 4),
  "ltv_cac" numeric(10, 4),
  "payback_period_months" numeric(10, 2),
  "conversion_rate" numeric(10, 4),
  "cpl" numeric(18, 4),
  "sales_cycle_length_days" numeric(10, 2),
  "win_rate" numeric(10, 4),
  "dau_mau_ratio" numeric(10, 4),
  "feature_adoption_rate" numeric(10, 4),
  "time_to_value_days" numeric(10, 2),
  "nps" numeric(10, 2),
  "burn_rate" numeric(18, 4),
  "runway_months" numeric(10, 2),
  "gross_margin" numeric(10, 4),
  "operating_margin" numeric(10, 4),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "model_metrics_model_id_idx" ON "model_metrics" ("model_id");
