/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as CompanyNewRouteImport } from './routes/company/new'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CompanyCompanyIdRouteRouteImport } from './routes/company/$companyId/route'
import { Route as CompanyCompanyIdIndexRouteImport } from './routes/company/$companyId/index'
import { Route as CompanyCompanyIdTeamRouteImport } from './routes/company/$companyId/team'
import { Route as CompanyCompanyIdRolesRouteImport } from './routes/company/$companyId/roles'
import { Route as CompanyCompanyIdApplicationsRouteImport } from './routes/company/$companyId/applications'
import { Route as ApiPolarWebhooksRouteImport } from './routes/api/polar/webhooks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CompanyCompanyIdRolesIndexRouteImport } from './routes/company/$companyId/roles.index'
import { Route as CompanyCompanyIdApplicationsIndexRouteImport } from './routes/company/$companyId/applications.index'
import { Route as CompanyCompanyIdRolesJobIdRouteImport } from './routes/company/$companyId/roles.$jobId'
import { Route as CompanyCompanyIdApplicationsApplicationIdRouteImport } from './routes/company/$companyId/applications.$applicationId'
import { Route as CompanyCompanyIdRolesJobIdIndexRouteImport } from './routes/company/$companyId/roles.$jobId.index'
import { Route as CompanyCompanyIdRolesJobIdPreviewRouteImport } from './routes/company/$companyId/roles.$jobId.preview'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyNewRoute = CompanyNewRouteImport.update({
  id: '/company/new',
  path: '/company/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRouteRoute = CompanyCompanyIdRouteRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdIndexRoute = CompanyCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyCompanyIdRouteRoute,
} as any)
const CompanyCompanyIdTeamRoute = CompanyCompanyIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CompanyCompanyIdRouteRoute,
} as any)
const CompanyCompanyIdRolesRoute = CompanyCompanyIdRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => CompanyCompanyIdRouteRoute,
} as any)
const CompanyCompanyIdApplicationsRoute =
  CompanyCompanyIdApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => CompanyCompanyIdRouteRoute,
  } as any)
const ApiPolarWebhooksRoute = ApiPolarWebhooksRouteImport.update({
  id: '/api/polar/webhooks',
  path: '/api/polar/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRolesIndexRoute =
  CompanyCompanyIdRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanyCompanyIdRolesRoute,
  } as any)
const CompanyCompanyIdApplicationsIndexRoute =
  CompanyCompanyIdApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanyCompanyIdApplicationsRoute,
  } as any)
const CompanyCompanyIdRolesJobIdRoute =
  CompanyCompanyIdRolesJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => CompanyCompanyIdRolesRoute,
  } as any)
const CompanyCompanyIdApplicationsApplicationIdRoute =
  CompanyCompanyIdApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => CompanyCompanyIdApplicationsRoute,
  } as any)
const CompanyCompanyIdRolesJobIdIndexRoute =
  CompanyCompanyIdRolesJobIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanyCompanyIdRolesJobIdRoute,
  } as any)
const CompanyCompanyIdRolesJobIdPreviewRoute =
  CompanyCompanyIdRolesJobIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => CompanyCompanyIdRolesJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/profile': typeof ProfileRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/company/new': typeof CompanyNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/company/': typeof CompanyIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/company/$companyId/applications': typeof CompanyCompanyIdApplicationsRouteWithChildren
  '/company/$companyId/roles': typeof CompanyCompanyIdRolesRouteWithChildren
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/company/$companyId/': typeof CompanyCompanyIdIndexRoute
  '/company/$companyId/applications/$applicationId': typeof CompanyCompanyIdApplicationsApplicationIdRoute
  '/company/$companyId/roles/$jobId': typeof CompanyCompanyIdRolesJobIdRouteWithChildren
  '/company/$companyId/applications/': typeof CompanyCompanyIdApplicationsIndexRoute
  '/company/$companyId/roles/': typeof CompanyCompanyIdRolesIndexRoute
  '/company/$companyId/roles/$jobId/preview': typeof CompanyCompanyIdRolesJobIdPreviewRoute
  '/company/$companyId/roles/$jobId/': typeof CompanyCompanyIdRolesJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/company/new': typeof CompanyNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/company': typeof CompanyIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/company/$companyId': typeof CompanyCompanyIdIndexRoute
  '/company/$companyId/applications/$applicationId': typeof CompanyCompanyIdApplicationsApplicationIdRoute
  '/company/$companyId/applications': typeof CompanyCompanyIdApplicationsIndexRoute
  '/company/$companyId/roles': typeof CompanyCompanyIdRolesIndexRoute
  '/company/$companyId/roles/$jobId/preview': typeof CompanyCompanyIdRolesJobIdPreviewRoute
  '/company/$companyId/roles/$jobId': typeof CompanyCompanyIdRolesJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/profile': typeof ProfileRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/company/new': typeof CompanyNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/company/': typeof CompanyIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/company/$companyId/applications': typeof CompanyCompanyIdApplicationsRouteWithChildren
  '/company/$companyId/roles': typeof CompanyCompanyIdRolesRouteWithChildren
  '/company/$companyId/team': typeof CompanyCompanyIdTeamRoute
  '/company/$companyId/': typeof CompanyCompanyIdIndexRoute
  '/company/$companyId/applications/$applicationId': typeof CompanyCompanyIdApplicationsApplicationIdRoute
  '/company/$companyId/roles/$jobId': typeof CompanyCompanyIdRolesJobIdRouteWithChildren
  '/company/$companyId/applications/': typeof CompanyCompanyIdApplicationsIndexRoute
  '/company/$companyId/roles/': typeof CompanyCompanyIdRolesIndexRoute
  '/company/$companyId/roles/$jobId/preview': typeof CompanyCompanyIdRolesJobIdPreviewRoute
  '/company/$companyId/roles/$jobId/': typeof CompanyCompanyIdRolesJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/profile'
    | '/company/$companyId'
    | '/auth/callback'
    | '/auth/signin'
    | '/auth/signup'
    | '/billing/success'
    | '/companies/$slug'
    | '/company/new'
    | '/jobs/$jobId'
    | '/company/'
    | '/jobs/'
    | '/api/auth/$'
    | '/api/polar/webhooks'
    | '/company/$companyId/applications'
    | '/company/$companyId/roles'
    | '/company/$companyId/team'
    | '/company/$companyId/'
    | '/company/$companyId/applications/$applicationId'
    | '/company/$companyId/roles/$jobId'
    | '/company/$companyId/applications/'
    | '/company/$companyId/roles/'
    | '/company/$companyId/roles/$jobId/preview'
    | '/company/$companyId/roles/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/profile'
    | '/auth/callback'
    | '/auth/signin'
    | '/auth/signup'
    | '/billing/success'
    | '/companies/$slug'
    | '/company/new'
    | '/jobs/$jobId'
    | '/company'
    | '/jobs'
    | '/api/auth/$'
    | '/api/polar/webhooks'
    | '/company/$companyId/team'
    | '/company/$companyId'
    | '/company/$companyId/applications/$applicationId'
    | '/company/$companyId/applications'
    | '/company/$companyId/roles'
    | '/company/$companyId/roles/$jobId/preview'
    | '/company/$companyId/roles/$jobId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/profile'
    | '/company/$companyId'
    | '/auth/callback'
    | '/auth/signin'
    | '/auth/signup'
    | '/billing/success'
    | '/companies/$slug'
    | '/company/new'
    | '/jobs/$jobId'
    | '/company/'
    | '/jobs/'
    | '/api/auth/$'
    | '/api/polar/webhooks'
    | '/company/$companyId/applications'
    | '/company/$companyId/roles'
    | '/company/$companyId/team'
    | '/company/$companyId/'
    | '/company/$companyId/applications/$applicationId'
    | '/company/$companyId/roles/$jobId'
    | '/company/$companyId/applications/'
    | '/company/$companyId/roles/'
    | '/company/$companyId/roles/$jobId/preview'
    | '/company/$companyId/roles/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ProfileRoute: typeof ProfileRoute
  CompanyCompanyIdRouteRoute: typeof CompanyCompanyIdRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  CompanyNewRoute: typeof CompanyNewRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPolarWebhooksRoute: typeof ApiPolarWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/new': {
      id: '/company/new'
      path: '/company/new'
      fullPath: '/company/new'
      preLoaderRoute: typeof CompanyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId/': {
      id: '/company/$companyId/'
      path: '/'
      fullPath: '/company/$companyId/'
      preLoaderRoute: typeof CompanyCompanyIdIndexRouteImport
      parentRoute: typeof CompanyCompanyIdRouteRoute
    }
    '/company/$companyId/team': {
      id: '/company/$companyId/team'
      path: '/team'
      fullPath: '/company/$companyId/team'
      preLoaderRoute: typeof CompanyCompanyIdTeamRouteImport
      parentRoute: typeof CompanyCompanyIdRouteRoute
    }
    '/company/$companyId/roles': {
      id: '/company/$companyId/roles'
      path: '/roles'
      fullPath: '/company/$companyId/roles'
      preLoaderRoute: typeof CompanyCompanyIdRolesRouteImport
      parentRoute: typeof CompanyCompanyIdRouteRoute
    }
    '/company/$companyId/applications': {
      id: '/company/$companyId/applications'
      path: '/applications'
      fullPath: '/company/$companyId/applications'
      preLoaderRoute: typeof CompanyCompanyIdApplicationsRouteImport
      parentRoute: typeof CompanyCompanyIdRouteRoute
    }
    '/api/polar/webhooks': {
      id: '/api/polar/webhooks'
      path: '/api/polar/webhooks'
      fullPath: '/api/polar/webhooks'
      preLoaderRoute: typeof ApiPolarWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId/roles/': {
      id: '/company/$companyId/roles/'
      path: '/'
      fullPath: '/company/$companyId/roles/'
      preLoaderRoute: typeof CompanyCompanyIdRolesIndexRouteImport
      parentRoute: typeof CompanyCompanyIdRolesRoute
    }
    '/company/$companyId/applications/': {
      id: '/company/$companyId/applications/'
      path: '/'
      fullPath: '/company/$companyId/applications/'
      preLoaderRoute: typeof CompanyCompanyIdApplicationsIndexRouteImport
      parentRoute: typeof CompanyCompanyIdApplicationsRoute
    }
    '/company/$companyId/roles/$jobId': {
      id: '/company/$companyId/roles/$jobId'
      path: '/$jobId'
      fullPath: '/company/$companyId/roles/$jobId'
      preLoaderRoute: typeof CompanyCompanyIdRolesJobIdRouteImport
      parentRoute: typeof CompanyCompanyIdRolesRoute
    }
    '/company/$companyId/applications/$applicationId': {
      id: '/company/$companyId/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/company/$companyId/applications/$applicationId'
      preLoaderRoute: typeof CompanyCompanyIdApplicationsApplicationIdRouteImport
      parentRoute: typeof CompanyCompanyIdApplicationsRoute
    }
    '/company/$companyId/roles/$jobId/': {
      id: '/company/$companyId/roles/$jobId/'
      path: '/'
      fullPath: '/company/$companyId/roles/$jobId/'
      preLoaderRoute: typeof CompanyCompanyIdRolesJobIdIndexRouteImport
      parentRoute: typeof CompanyCompanyIdRolesJobIdRoute
    }
    '/company/$companyId/roles/$jobId/preview': {
      id: '/company/$companyId/roles/$jobId/preview'
      path: '/preview'
      fullPath: '/company/$companyId/roles/$jobId/preview'
      preLoaderRoute: typeof CompanyCompanyIdRolesJobIdPreviewRouteImport
      parentRoute: typeof CompanyCompanyIdRolesJobIdRoute
    }
  }
}

interface CompanyCompanyIdApplicationsRouteChildren {
  CompanyCompanyIdApplicationsApplicationIdRoute: typeof CompanyCompanyIdApplicationsApplicationIdRoute
  CompanyCompanyIdApplicationsIndexRoute: typeof CompanyCompanyIdApplicationsIndexRoute
}

const CompanyCompanyIdApplicationsRouteChildren: CompanyCompanyIdApplicationsRouteChildren =
  {
    CompanyCompanyIdApplicationsApplicationIdRoute:
      CompanyCompanyIdApplicationsApplicationIdRoute,
    CompanyCompanyIdApplicationsIndexRoute:
      CompanyCompanyIdApplicationsIndexRoute,
  }

const CompanyCompanyIdApplicationsRouteWithChildren =
  CompanyCompanyIdApplicationsRoute._addFileChildren(
    CompanyCompanyIdApplicationsRouteChildren,
  )

interface CompanyCompanyIdRolesJobIdRouteChildren {
  CompanyCompanyIdRolesJobIdPreviewRoute: typeof CompanyCompanyIdRolesJobIdPreviewRoute
  CompanyCompanyIdRolesJobIdIndexRoute: typeof CompanyCompanyIdRolesJobIdIndexRoute
}

const CompanyCompanyIdRolesJobIdRouteChildren: CompanyCompanyIdRolesJobIdRouteChildren =
  {
    CompanyCompanyIdRolesJobIdPreviewRoute:
      CompanyCompanyIdRolesJobIdPreviewRoute,
    CompanyCompanyIdRolesJobIdIndexRoute: CompanyCompanyIdRolesJobIdIndexRoute,
  }

const CompanyCompanyIdRolesJobIdRouteWithChildren =
  CompanyCompanyIdRolesJobIdRoute._addFileChildren(
    CompanyCompanyIdRolesJobIdRouteChildren,
  )

interface CompanyCompanyIdRolesRouteChildren {
  CompanyCompanyIdRolesJobIdRoute: typeof CompanyCompanyIdRolesJobIdRouteWithChildren
  CompanyCompanyIdRolesIndexRoute: typeof CompanyCompanyIdRolesIndexRoute
}

const CompanyCompanyIdRolesRouteChildren: CompanyCompanyIdRolesRouteChildren = {
  CompanyCompanyIdRolesJobIdRoute: CompanyCompanyIdRolesJobIdRouteWithChildren,
  CompanyCompanyIdRolesIndexRoute: CompanyCompanyIdRolesIndexRoute,
}

const CompanyCompanyIdRolesRouteWithChildren =
  CompanyCompanyIdRolesRoute._addFileChildren(
    CompanyCompanyIdRolesRouteChildren,
  )

interface CompanyCompanyIdRouteRouteChildren {
  CompanyCompanyIdApplicationsRoute: typeof CompanyCompanyIdApplicationsRouteWithChildren
  CompanyCompanyIdRolesRoute: typeof CompanyCompanyIdRolesRouteWithChildren
  CompanyCompanyIdTeamRoute: typeof CompanyCompanyIdTeamRoute
  CompanyCompanyIdIndexRoute: typeof CompanyCompanyIdIndexRoute
}

const CompanyCompanyIdRouteRouteChildren: CompanyCompanyIdRouteRouteChildren = {
  CompanyCompanyIdApplicationsRoute:
    CompanyCompanyIdApplicationsRouteWithChildren,
  CompanyCompanyIdRolesRoute: CompanyCompanyIdRolesRouteWithChildren,
  CompanyCompanyIdTeamRoute: CompanyCompanyIdTeamRoute,
  CompanyCompanyIdIndexRoute: CompanyCompanyIdIndexRoute,
}

const CompanyCompanyIdRouteRouteWithChildren =
  CompanyCompanyIdRouteRoute._addFileChildren(
    CompanyCompanyIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  ProfileRoute: ProfileRoute,
  CompanyCompanyIdRouteRoute: CompanyCompanyIdRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  CompanyNewRoute: CompanyNewRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPolarWebhooksRoute: ApiPolarWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
